theme = "blowfish"
baseURL = "https://zakk.au/"
defaultContentLanguage = "en"
disableLanguages = []
hasCJKLanguage = true
title = "Zakk"

enableRobotsTXT = true
summaryLength = 30
buildDrafts = false
buildFuture = false
enableEmoji = true

[pagination]
  pagerSize = 10

[imaging]
  anchor = "Center"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = "always"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 100

  [[related.indices]]
    name = "series"
    weight = 50

  [[related.indices]]
    name = "authors"
    weight = 20

  [[related.indices]]
    name = "date"
    weight = 10

  [[related.indices]]
    name = "fragmentrefs"
    weight = 10
    type = "fragments"
    applyFilter = false

[permalinks]
  posts = "/posts/:slug/"
