baseURL = "https://zakk.au/"
canonifyURLs = true
title = "Zakk"
theme = "blowfish"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true
enableRobotsTXT = true
summaryLength = 30

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100

  [[related.indices]]
    name = "categories"
    weight = 80

  [[related.indices]]
    name = "series"
    weight = 60

  [[related.indices]]
    name = "date"
    weight = 10

[permalinks]
  posts = "/posts/:slug/"
