# -- Main Menu --
# 正體中文版頭部導航。

[[main]]
	identifier = "about"
	name = "關於我"
	pageRef = "about"
	weight = 10

[[main]]
	identifier = "posts"
	name = "文章"
	pageRef = "posts"
	weight = 20

[[main]]
	identifier = "timeline"
	name = "時間軸"
	pageRef = "timeline"
	weight = 30

[[main]]
	identifier = "github"
	pre = "github"
	url = "https://github.com/Zakkaus"
	weight = 200

[[main]]
	identifier = "instagram"
	pre = "instagram"
	url = "https://www.instagram.com/zakk.au/"
	weight = 210

[[main]]
	identifier = "x-twitter"
	pre = "x-twitter"
	url = "https://x.com/zakkauu"
	weight = 220

[[main]]
	identifier = "email"
	pre = "email"
	url = "mailto:admin@zakk.au"
	weight = 230

# -- Footer Menu --
# 正體中文版頁腳導航。

[[footer]]
	identifier = "about"
	name = "關於我"
	pageRef = "about"
	weight = 10

[[footer]]
	identifier = "timeline"
	name = "時間軸"
	pageRef = "timeline"
	weight = 20

[[footer]]
	identifier = "tags"
	name = "標籤"
	pageRef = "tags"
	weight = 30
