[[main]]
  identifier = "about"
  name = "關於我"
  url = "/zh-hant/about/"
  weight = 10

[[main]]
  identifier = "posts"
  name = "文章"
  url = "/zh-hant/posts/"
  weight = 20

[[main]]
  identifier = "timeline"
  name = "時間軸"
  url = "/zh-hant/timeline/"
  weight = 30
