[[main]]
  name = "關於我"
  pageRef = "about"
  weight = 10

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "時間軸"
  pageRef = "timeline"
  weight = 30

[[main]]
  identifier = "en"
  name = "English"
  url = "/"
  weight = 100

[[footer]]
  name = "關於我"
  pageRef = "about"
  weight = 10

[[footer]]
  name = "時間軸"
  pageRef = "timeline"
  weight = 20

[[footer]]
  name = "標籤"
  pageRef = "tags"
  weight = 30
