# -- Main Menu --
# Configure header navigation for the Traditional Chinese locale.

[[main]]
  name = "關於我"
  page = "about"
  url = "/zh-tw/about/"
  weight = 10

[[main]]
  name = "文章"
  page = "posts"
  url = "/zh-tw/posts/"
  weight = 20

[[main]]
  name = "時間軸"
  page = "timeline"
  url = "/zh-tw/timeline/"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/Zakkaus"
  weight = 200

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://www.instagram.com/zakk.au/"
  weight = 210

[[main]]
  identifier = "x-twitter"
  pre = "x-twitter"
  url = "https://x.com/zakkauu"
  weight = 220

[[main]]
  identifier = "email"
  pre = "email"
  url = "mailto:admin@zakk.au"
  weight = 230

# -- Footer Menu --
# Configure footer navigation for the Traditional Chinese locale.

[[footer]]
  name = "關於我"
  page = "about"
  url = "/zh-tw/about/"
  weight = 10

[[footer]]
  name = "時間軸"
  page = "timeline"
  url = "/zh-tw/timeline/"
  weight = 20

[[footer]]
  name = "標籤"
  pageRef = "tags"
  weight = 30
