[[main]]
  name = "關於我"
  url = "/zh-hant/about/"
  weight = 10

[[main]]
  name = "文章"
  url = "/zh-hant/posts/"
  weight = 20

[[main]]
  name = "時間軸"
  url = "/zh-hant/timeline/"
  weight = 30

[[footer]]
  name = "關於我"
  pageRef = "about"
  weight = 10

[[footer]]
  name = "時間軸"
  pageRef = "timeline"
  weight = 20

[[footer]]
  name = "標籤"
  pageRef = "tags"
  weight = 30
