# -- Main Menu --
# Configure header navigation for the Traditional Chinese locale.

[[main]]
  name = "關於我"
  pageRef = "about"
  weight = 10

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "時間軸"
  pageRef = "timeline"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/Zakkaus"
  weight = 200

[[main]]
  # This file is intentionally kept empty. Traditional Chinese menus are defined in
  # `config/_default/languages.zh-tw.toml`.
  url = "https://www.instagram.com/zakk.au/"
