[[main]]
  name = "关于我"
  pageRef = "about"
  lang = "zh-cn"
  weight = 10

[[main]]
  name = "文章"
  pageRef = "posts"
  lang = "zh-cn"
  weight = 20

[[main]]
  name = "时间轴"
  pageRef = "timeline"
  lang = "zh-cn"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/Zakkaus"
  lang = "zh-cn"
  weight = 200

[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://www.instagram.com/zakk.au/"
  lang = "zh-cn"
  weight = 210

[[main]]
  identifier = "x-twitter"
  pre = "x-twitter"
  url = "https://x.com/zakkauu"
  lang = "zh-cn"
  weight = 220

[[main]]
  # Local menus configured in `config/_default/languages.zh-cn.toml`.
  pre = "email"
